character_name = input("Please fill in the following information below\nCharacter Name: ")
ch_class = input("Character Class (e.g., Sorcerer, Knight, Archer): ")
home_realm = input("Home Realm (e.g., “Whispering Woods”): ")
s_a = input("Special Ability (e.g., “Fireball”): ")
ch_w = input("Chosen Weapon: ")
print("========================================")
print("     -- CHARACTER CREATION COMPLETE --")
print("========================================")
print()
print("Name:     "+character_name)
print("Class:    "+ch_class)
print("Realm:    "+home_realm)
print()
print("Title: " + character_name + " the " + ch_class + " of " + home_realm)
print()
print("----------------------------------------")
print("Weapon of Choice: " + ch_w)
print("Special Ability: " + s_a)
print("========================================")